
#    a_st_a_service_tracking.example:
#        class: AStAService\TrackingBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    astaservice.tracking:
        class: AStAService\TrackingBundle\Services\TrackingService
        arguments: [ @doctrine.orm.entity_manager ]

